[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node admin/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1
