-- ============================================================================
-- supabase-bootstrap.sql
-- Generated by scripts/supabase-1-dump-schema.js
-- Source: Railway Postgres (gondola.proxy.rlwy.net:27298) 2026-05-20T01:52:34.362Z
-- Target: Supabase Free tier project AccessSync (us-west-1)
-- Path B (Node pg + Supabase MCP) per DR-047 / OB-180
-- ============================================================================

-- --- Extensions ---
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- --- Tables ---

CREATE TABLE "activity_event" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "trace_id" character varying(36) NOT NULL,
  "ts" timestamp with time zone DEFAULT now() NOT NULL,
  "client_id" uuid,
  "actor_type" character varying(20) NOT NULL,
  "actor_id" character varying(64) NOT NULL,
  "action" character varying(80) NOT NULL,
  "target_type" character varying(40),
  "target_id" character varying(64),
  "result" character varying(20) DEFAULT 'success'::character varying NOT NULL,
  "diff" jsonb,
  "request_meta" jsonb
);

CREATE TABLE "adapter_admin_log" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "event_type" character varying(100) NOT NULL,
  "platform_member_id" character varying(255),
  "hardware_user_id" character varying(255),
  "role_assignment_id" character varying(255),
  "result" character varying(50),
  "configured_by" character varying(255),
  "configured_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "admin_action" character varying(100),
  "details" jsonb,
  "target_entity" character varying(50),
  "target_id" uuid,
  "trace_id" character varying(36),
  "actor_type" character varying(20),
  "actor_id" character varying(64)
);

CREATE TABLE "as_client_subscriptions" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "location_id" uuid,
  "term_id" uuid,
  "status" character varying(50) DEFAULT 'trial'::character varying NOT NULL,
  "override_active" boolean DEFAULT false NOT NULL,
  "override_reason" text,
  "override_set_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "as_subscription_terms" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "name" character varying(100) NOT NULL,
  "billing_cadence" character varying(50),
  "base_price" numeric(10,2),
  "discount_amount" numeric(10,2),
  "discount_percent" numeric(5,2),
  "is_free" boolean DEFAULT false NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "effective_start" timestamp with time zone,
  "effective_end" timestamp with time zone,
  "description" text,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "billing_subscriptions" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "location_id" uuid,
  "tier" character varying(50),
  "status" character varying(50) DEFAULT 'active'::character varying NOT NULL,
  "subscribed_at" timestamp with time zone,
  "wix_subscription_id" character varying(255),
  "effective_start" timestamp with time zone,
  "effective_end" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "client_activity_summary" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "summary_date" date NOT NULL,
  "events_received" integer DEFAULT 0,
  "grants_completed" integer DEFAULT 0,
  "revokes_completed" integer DEFAULT 0,
  "errors_count" integer DEFAULT 0,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "clients" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "name" character varying(255) NOT NULL,
  "status" character varying(50) DEFAULT 'active'::character varying,
  "source_site_id" character varying(255),
  "notification_email" character varying(255),
  "last_sync_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "platform" character varying(50) DEFAULT 'wix'::character varying NOT NULL,
  "source_site_name" character varying(255),
  "source_site_url" character varying(255),
  "last_webhook_at" timestamp with time zone,
  "first_grant_sent" boolean DEFAULT false NOT NULL,
  "archived_at" timestamp with time zone,
  "source_api_key" text,
  "platform_instance_id" character varying(255),
  "reconciliation_interval" character varying(20) DEFAULT 'daily'::character varying,
  "last_active_member_count" integer
);

CREATE TABLE "config_alert_log" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid,
  "alert_type" character varying(100) NOT NULL,
  "plan_mapping_id" uuid,
  "hardware_ref" character varying(255),
  "affected_member_count" integer DEFAULT 0,
  "resolved_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "last_seen_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "trace_id" character varying(36),
  "actor_type" character varying(20),
  "actor_id" character varying(64)
);

CREATE TABLE "connector_subscriptions" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "hardware_platform" character varying(50) NOT NULL,
  "hardware_api_key" text,
  "kisi_user_pattern" character varying(20) DEFAULT 'invited'::character varying NOT NULL,
  "status" character varying(50) DEFAULT 'active'::character varying,
  "key_last_verified" timestamp with time zone,
  "key_last_error" text,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "diagnostic_log" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "client_id" uuid,
  "service" character varying(100) NOT NULL,
  "level" character varying(20) NOT NULL,
  "error_code" character varying(100) NOT NULL,
  "message" text NOT NULL,
  "context" jsonb DEFAULT '{}'::jsonb,
  "resolved_at" timestamp with time zone,
  "trace_id" text,
  "actor_type" character varying(20),
  "actor_id" character varying(64)
);

CREATE TABLE "error_queue" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid,
  "member_id" uuid,
  "event_type" character varying(100),
  "payload" jsonb,
  "error_reason" text,
  "retry_count" integer DEFAULT 0,
  "status" character varying(50) DEFAULT 'failed'::character varying,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "resolved_at" timestamp with time zone,
  "dismiss_note" text,
  "dismissed_by" character varying(255),
  "location_id" uuid,
  "plan_name" character varying(255),
  "door_name" character varying(255),
  "error_code" text,
  "user_message" text,
  "resolution" text,
  "action_text" text,
  "http_status" integer,
  "raw_api_body" jsonb,
  "occurred_count" integer DEFAULT 1,
  "last_occurred_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "trace_id" character varying(36),
  "actor_type" character varying(20),
  "actor_id" character varying(64)
);

CREATE TABLE "locations" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "name" character varying(255) NOT NULL,
  "city" character varying(100),
  "state" character varying(50),
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "notification_email" character varying(255)
);

CREATE TABLE "member_access" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "member_master_id" uuid NOT NULL,
  "client_id" uuid NOT NULL,
  "hardware_platform" character varying(50),
  "hardware_user_id" character varying(255),
  "source_platform" character varying(50),
  "platform_member_id" character varying(255),
  "status" character varying(50) DEFAULT 'pending'::character varying NOT NULL,
  "provisioned_at" timestamp with time zone,
  "sub_master_id" uuid,
  "plan_holder" boolean DEFAULT false,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "member_access_log" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "member_id" uuid NOT NULL,
  "client_id" uuid NOT NULL,
  "event_type" character varying(100) NOT NULL,
  "credential_type" character varying(50),
  "credential_value" text,
  "error_code" character varying(50),
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "trace_id" character varying(36),
  "actor_type" character varying(20),
  "actor_id" character varying(64),
  "mapping_id" uuid,
  "hardware_group_id" character varying(64)
);

CREATE TABLE "member_access_sources" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "access_id" uuid NOT NULL,
  "billing_id" uuid,
  "source_type" character varying(50),
  "source_plan_id" character varying(255),
  "hardware_group_id" character varying(255),
  "role_assignment_id" character varying(255),
  "mapping_id" uuid,
  "effective_start" timestamp with time zone,
  "valid_until" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "status" character varying(50) DEFAULT 'active'::character varying NOT NULL,
  "provisioned_at" timestamp with time zone,
  "scheduled_start_date" timestamp with time zone,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "client_id" uuid NOT NULL
);

CREATE TABLE "member_billing" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "member_master_id" uuid NOT NULL,
  "client_id" uuid NOT NULL,
  "wix_order_id" character varying(255) NOT NULL,
  "wix_subscription_id" character varying(255),
  "cycle_index" integer DEFAULT 1 NOT NULL,
  "plan_id" character varying(255),
  "plan_name" character varying(255),
  "effective_start" timestamp with time zone,
  "effective_end" timestamp with time zone,
  "status" character varying(50) DEFAULT 'active'::character varying NOT NULL,
  "billing_snapshot" jsonb,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "member_master" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "source_platform" character varying(50) NOT NULL,
  "platform_member_id" character varying(255) NOT NULL,
  "email" character varying(255),
  "first_name" character varying(255),
  "last_name" character varying(255),
  "display_name" character varying(255),
  "phone" character varying(50),
  "source_tag" character varying(50) DEFAULT 'accesssync'::character varying,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "plan_mapping_groups" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "mapping_id" uuid NOT NULL,
  "hardware_group_id" character varying(255) NOT NULL,
  "door_name" character varying(255),
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "health_status" character varying(20) DEFAULT 'ok'::character varying
);

CREATE TABLE "plan_mappings" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "source_plan_id" character varying(255) NOT NULL,
  "hardware_group_id" character varying(255),
  "tier_name" character varying(50) DEFAULT 'Base'::character varying,
  "action" character varying(50) DEFAULT 'grant'::character varying,
  "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "location_id" uuid,
  "plan_name" character varying(255),
  "door_name" character varying(255),
  "status" character varying(50) DEFAULT 'active'::character varying,
  "access_type" character varying(50) DEFAULT 'group'::character varying,
  "allow_multiple" boolean DEFAULT false,
  "max_members" integer DEFAULT 1,
  "source_status" character varying(20) DEFAULT 'active'::character varying
);

CREATE TABLE "processed_event_ids" (
  "event_id" character varying(255) NOT NULL,
  "client_id" uuid,
  "processed_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "reconciliation_run" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "client_id" uuid NOT NULL,
  "trace_id" character varying(64),
  "triggered_by" character varying(32) NOT NULL,
  "triggered_by_actor_type" character varying(32),
  "triggered_by_actor_id" character varying(128),
  "started_at" timestamp with time zone DEFAULT now() NOT NULL,
  "completed_at" timestamp with time zone,
  "status" character varying(32) DEFAULT 'running'::character varying NOT NULL,
  "abort_reason" character varying(64),
  "wix_active_count" integer,
  "kisi_managed_count" integer,
  "grants_queued" integer DEFAULT 0 NOT NULL,
  "revokes_queued" integer DEFAULT 0 NOT NULL,
  "grants_skipped_optin" integer DEFAULT 0 NOT NULL,
  "sanity_gate_triggered" boolean DEFAULT false NOT NULL,
  "sanity_gate_resolved" boolean,
  "notes" text
);

CREATE TABLE "trace_context" (
  "trace_id" character varying(36) NOT NULL,
  "started_at" timestamp with time zone DEFAULT now() NOT NULL,
  "client_id" uuid,
  "client_name" character varying(255),
  "member_id" uuid,
  "member_name" character varying(255),
  "member_email" character varying(255),
  "platform_member_id" character varying(255),
  "source_platform" character varying(50),
  "hardware_platform" character varying(50),
  "hardware_user_id" character varying(64),
  "plan_name" character varying(255),
  "door_name" character varying(255),
  "mapping_id" uuid,
  "actor_type" character varying(20),
  "actor_id" character varying(64),
  "entry_point" character varying(50)
);

CREATE TABLE "webhook_log" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "event_id" character varying(255),
  "client_id" uuid,
  "received_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "hmac_status" character varying(20) NOT NULL,
  "dedup_status" character varying(20),
  "event_type" character varying(100),
  "raw_payload" jsonb,
  "normalized_payload" jsonb,
  "error_detail" text,
  "trace_id" text,
  "actor_type" character varying(20),
  "actor_id" character varying(64)
);

-- --- Primary keys ---
ALTER TABLE "activity_event" ADD CONSTRAINT "activity_event_pkey" PRIMARY KEY (id);
ALTER TABLE "adapter_admin_log" ADD CONSTRAINT "adapter_admin_log_pkey" PRIMARY KEY (id);
ALTER TABLE "as_client_subscriptions" ADD CONSTRAINT "as_client_subscriptions_pkey" PRIMARY KEY (id);
ALTER TABLE "as_subscription_terms" ADD CONSTRAINT "as_subscription_terms_pkey" PRIMARY KEY (id);
ALTER TABLE "billing_subscriptions" ADD CONSTRAINT "billing_subscriptions_pkey" PRIMARY KEY (id);
ALTER TABLE "client_activity_summary" ADD CONSTRAINT "client_activity_summary_pkey" PRIMARY KEY (id);
ALTER TABLE "clients" ADD CONSTRAINT "clients_pkey" PRIMARY KEY (id);
ALTER TABLE "config_alert_log" ADD CONSTRAINT "config_alert_log_pkey" PRIMARY KEY (id);
ALTER TABLE "connector_subscriptions" ADD CONSTRAINT "connector_subscriptions_pkey" PRIMARY KEY (id);
ALTER TABLE "diagnostic_log" ADD CONSTRAINT "diagnostic_log_pkey" PRIMARY KEY (id);
ALTER TABLE "error_queue" ADD CONSTRAINT "error_queue_pkey" PRIMARY KEY (id);
ALTER TABLE "locations" ADD CONSTRAINT "locations_pkey" PRIMARY KEY (id);
ALTER TABLE "member_access" ADD CONSTRAINT "member_access_pkey" PRIMARY KEY (id);
ALTER TABLE "member_access_log" ADD CONSTRAINT "member_access_log_pkey" PRIMARY KEY (id);
ALTER TABLE "member_access_sources" ADD CONSTRAINT "member_access_sources_pkey" PRIMARY KEY (id);
ALTER TABLE "member_billing" ADD CONSTRAINT "member_billing_pkey" PRIMARY KEY (id);
ALTER TABLE "member_master" ADD CONSTRAINT "member_master_pkey" PRIMARY KEY (id);
ALTER TABLE "plan_mapping_groups" ADD CONSTRAINT "plan_mapping_groups_pkey" PRIMARY KEY (id);
ALTER TABLE "plan_mappings" ADD CONSTRAINT "plan_mappings_pkey" PRIMARY KEY (id);
ALTER TABLE "processed_event_ids" ADD CONSTRAINT "processed_event_ids_pkey" PRIMARY KEY (event_id);
ALTER TABLE "reconciliation_run" ADD CONSTRAINT "reconciliation_run_pkey" PRIMARY KEY (id);
ALTER TABLE "trace_context" ADD CONSTRAINT "trace_context_pkey" PRIMARY KEY (trace_id);
ALTER TABLE "webhook_log" ADD CONSTRAINT "webhook_log_pkey" PRIMARY KEY (id);

-- --- Unique constraints ---
ALTER TABLE "as_client_subscriptions" ADD CONSTRAINT "as_client_subscriptions_client_id_location_id_key" UNIQUE (client_id, location_id);
ALTER TABLE "as_subscription_terms" ADD CONSTRAINT "as_subscription_terms_name_key" UNIQUE (name);
ALTER TABLE "client_activity_summary" ADD CONSTRAINT "client_activity_summary_client_id_summary_date_key" UNIQUE (client_id, summary_date);
ALTER TABLE "clients" ADD CONSTRAINT "clients_wix_site_id_key" UNIQUE (source_site_id);
ALTER TABLE "connector_subscriptions" ADD CONSTRAINT "connector_subscriptions_client_id_hardware_platform_key" UNIQUE (client_id, hardware_platform);
ALTER TABLE "member_access" ADD CONSTRAINT "member_access_member_master_id_client_id_key" UNIQUE (member_master_id, client_id);
ALTER TABLE "member_access_sources" ADD CONSTRAINT "member_access_sources_client_access_source_plan_group_key" UNIQUE (client_id, access_id, source_type, source_plan_id, hardware_group_id);
ALTER TABLE "member_billing" ADD CONSTRAINT "member_billing_client_wix_order_cycle_key" UNIQUE (client_id, wix_order_id, cycle_index);
ALTER TABLE "member_master" ADD CONSTRAINT "member_master_client_id_source_platform_platform_member_id_key" UNIQUE (client_id, source_platform, platform_member_id);
ALTER TABLE "plan_mapping_groups" ADD CONSTRAINT "plan_mapping_groups_mapping_id_hardware_group_id_key" UNIQUE (mapping_id, hardware_group_id);

-- --- Check constraints ---
ALTER TABLE "connector_subscriptions" ADD CONSTRAINT "connector_subscriptions_kisi_user_pattern_check" CHECK (kisi_user_pattern::text = ANY (ARRAY['invited'::character varying, 'managed'::character varying]::text[]));
ALTER TABLE "diagnostic_log" ADD CONSTRAINT "diagnostic_log_level_check" CHECK (level::text = ANY (ARRAY['warn'::character varying, 'error'::character varying, 'critical'::character varying]::text[]));
ALTER TABLE "member_access" ADD CONSTRAINT "member_access_status_check" CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'in_flight'::character varying, 'pending_identity'::character varying, 'recovery_pending'::character varying]::text[]));
ALTER TABLE "member_access_sources" ADD CONSTRAINT "member_access_sources_status_check" CHECK (status::text = ANY (ARRAY['draft'::character varying, 'active'::character varying, 'pending_hardware'::character varying, 'pending_start'::character varying, 'failed'::character varying, 'cancelled'::character varying, 'revoked'::character varying]::text[]));

-- --- Indexes ---
CREATE INDEX idx_activity_event_action ON public.activity_event USING btree (action, ts DESC);
CREATE INDEX idx_activity_event_actor ON public.activity_event USING btree (actor_type, actor_id, ts DESC);
CREATE INDEX idx_activity_event_client ON public.activity_event USING btree (client_id, ts DESC) WHERE (client_id IS NOT NULL);
CREATE INDEX idx_activity_event_target ON public.activity_event USING btree (target_type, target_id, ts DESC) WHERE (target_id IS NOT NULL);
CREATE INDEX idx_activity_event_trace ON public.activity_event USING btree (trace_id);
CREATE INDEX idx_adapter_admin_log_actor ON public.adapter_admin_log USING btree (actor_type, actor_id) WHERE (actor_id IS NOT NULL);
CREATE INDEX idx_adapter_admin_log_trace ON public.adapter_admin_log USING btree (trace_id) WHERE (trace_id IS NOT NULL);
CREATE INDEX idx_as_client_subscriptions_client ON public.as_client_subscriptions USING btree (client_id);
CREATE INDEX idx_billing_subscriptions_location ON public.billing_subscriptions USING btree (location_id, status);
CREATE UNIQUE INDEX clients_platform_instance_id_idx ON public.clients USING btree (platform_instance_id) WHERE (platform_instance_id IS NOT NULL);
CREATE INDEX idx_config_alert_log_actor ON public.config_alert_log USING btree (actor_type, actor_id) WHERE (actor_id IS NOT NULL);
CREATE INDEX idx_config_alert_log_trace ON public.config_alert_log USING btree (trace_id) WHERE (trace_id IS NOT NULL);
CREATE INDEX idx_connector_subscriptions_client ON public.connector_subscriptions USING btree (client_id);
CREATE INDEX idx_diagnostic_log_actor ON public.diagnostic_log USING btree (actor_type, actor_id) WHERE (actor_id IS NOT NULL);
CREATE INDEX idx_diagnostic_log_client_code ON public.diagnostic_log USING btree (client_id, error_code, created_at DESC);
CREATE INDEX idx_diagnostic_log_client_created ON public.diagnostic_log USING btree (client_id, created_at DESC) WHERE (resolved_at IS NULL);
CREATE INDEX idx_diagnostic_log_platform ON public.diagnostic_log USING btree (created_at DESC) WHERE (client_id IS NULL);
CREATE INDEX idx_diagnostic_log_trace_id ON public.diagnostic_log USING btree (trace_id) WHERE (trace_id IS NOT NULL);
CREATE INDEX idx_error_queue_actor ON public.error_queue USING btree (actor_type, actor_id) WHERE (actor_id IS NOT NULL);
CREATE INDEX idx_error_queue_client_code ON public.error_queue USING btree (client_id, error_code, status);
CREATE INDEX idx_error_queue_dedup ON public.error_queue USING btree (client_id, member_id, error_code) WHERE ((status)::text = 'failed'::text);
CREATE INDEX idx_error_queue_trace ON public.error_queue USING btree (trace_id) WHERE (trace_id IS NOT NULL);
CREATE INDEX idx_member_access_client_status ON public.member_access USING btree (client_id, status);
CREATE INDEX idx_member_access_sub_master ON public.member_access USING btree (sub_master_id) WHERE (sub_master_id IS NOT NULL);
CREATE INDEX idx_member_access_log_actor ON public.member_access_log USING btree (actor_type, actor_id) WHERE (actor_id IS NOT NULL);
CREATE INDEX idx_member_access_log_mapping ON public.member_access_log USING btree (mapping_id) WHERE (mapping_id IS NOT NULL);
CREATE INDEX idx_member_access_log_member_created ON public.member_access_log USING btree (member_id, created_at DESC);
CREATE INDEX idx_member_access_log_trace ON public.member_access_log USING btree (trace_id) WHERE (trace_id IS NOT NULL);
CREATE INDEX idx_member_access_sources_access ON public.member_access_sources USING btree (access_id);
CREATE INDEX idx_member_access_sources_billing ON public.member_access_sources USING btree (billing_id) WHERE (billing_id IS NOT NULL);
CREATE INDEX idx_member_billing_master_status ON public.member_billing USING btree (member_master_id, status);
CREATE INDEX idx_member_billing_wix_order ON public.member_billing USING btree (wix_order_id);
CREATE INDEX idx_member_master_client_platform ON public.member_master USING btree (client_id, source_platform, platform_member_id);
CREATE INDEX idx_recon_run_client_started ON public.reconciliation_run USING btree (client_id, started_at DESC);
CREATE INDEX idx_recon_run_trace ON public.reconciliation_run USING btree (trace_id);
CREATE INDEX idx_trace_context_actor ON public.trace_context USING btree (actor_type, actor_id) WHERE (actor_id IS NOT NULL);
CREATE INDEX idx_trace_context_client ON public.trace_context USING btree (client_id, started_at DESC);
CREATE INDEX idx_trace_context_fts ON public.trace_context USING gin (to_tsvector('english'::regconfig, (((((((((((((COALESCE(client_name, ''::character varying))::text || ' '::text) || (COALESCE(member_name, ''::character varying))::text) || ' '::text) || (COALESCE(member_email, ''::character varying))::text) || ' '::text) || (COALESCE(platform_member_id, ''::character varying))::text) || ' '::text) || (COALESCE(hardware_user_id, ''::character varying))::text) || ' '::text) || (COALESCE(plan_name, ''::character varying))::text) || ' '::text) || (COALESCE(door_name, ''::character varying))::text)));
CREATE INDEX idx_trace_context_hardware ON public.trace_context USING btree (hardware_platform, hardware_user_id) WHERE (hardware_user_id IS NOT NULL);
CREATE INDEX idx_trace_context_member ON public.trace_context USING btree (member_id, started_at DESC);
CREATE INDEX idx_trace_context_source ON public.trace_context USING btree (source_platform) WHERE (source_platform IS NOT NULL);
CREATE INDEX idx_trace_context_started ON public.trace_context USING btree (started_at DESC);
CREATE INDEX idx_webhook_log_actor ON public.webhook_log USING btree (actor_type, actor_id) WHERE (actor_id IS NOT NULL);
CREATE INDEX idx_webhook_log_trace_id ON public.webhook_log USING btree (trace_id) WHERE (trace_id IS NOT NULL);

-- --- Foreign keys (last so all referenced tables exist) ---
ALTER TABLE "adapter_admin_log" ADD CONSTRAINT "adapter_admin_log_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE "as_client_subscriptions" ADD CONSTRAINT "as_client_subscriptions_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "as_client_subscriptions" ADD CONSTRAINT "as_client_subscriptions_location_id_fkey" FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL;
ALTER TABLE "as_client_subscriptions" ADD CONSTRAINT "as_client_subscriptions_term_id_fkey" FOREIGN KEY (term_id) REFERENCES as_subscription_terms(id) ON DELETE SET NULL;
ALTER TABLE "billing_subscriptions" ADD CONSTRAINT "billing_subscriptions_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "billing_subscriptions" ADD CONSTRAINT "billing_subscriptions_location_id_fkey" FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL;
ALTER TABLE "client_activity_summary" ADD CONSTRAINT "client_activity_summary_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE "config_alert_log" ADD CONSTRAINT "config_alert_log_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "config_alert_log" ADD CONSTRAINT "config_alert_log_plan_mapping_id_fkey" FOREIGN KEY (plan_mapping_id) REFERENCES plan_mappings(id);
ALTER TABLE "connector_subscriptions" ADD CONSTRAINT "connector_subscriptions_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "diagnostic_log" ADD CONSTRAINT "diagnostic_log_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "error_queue" ADD CONSTRAINT "error_queue_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE "error_queue" ADD CONSTRAINT "error_queue_location_id_fkey" FOREIGN KEY (location_id) REFERENCES locations(id);
ALTER TABLE "locations" ADD CONSTRAINT "locations_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "member_access" ADD CONSTRAINT "member_access_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "member_access" ADD CONSTRAINT "member_access_member_master_id_fkey" FOREIGN KEY (member_master_id) REFERENCES member_master(id) ON DELETE CASCADE;
ALTER TABLE "member_access" ADD CONSTRAINT "member_access_sub_master_id_fkey" FOREIGN KEY (sub_master_id) REFERENCES member_master(id);
ALTER TABLE "member_access_log" ADD CONSTRAINT "member_access_log_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "member_access_sources" ADD CONSTRAINT "member_access_sources_access_id_fkey" FOREIGN KEY (access_id) REFERENCES member_access(id) ON DELETE CASCADE;
ALTER TABLE "member_access_sources" ADD CONSTRAINT "member_access_sources_billing_id_fkey" FOREIGN KEY (billing_id) REFERENCES member_billing(id) ON DELETE SET NULL;
ALTER TABLE "member_access_sources" ADD CONSTRAINT "member_access_sources_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "member_access_sources" ADD CONSTRAINT "member_access_sources_mapping_id_fkey" FOREIGN KEY (mapping_id) REFERENCES plan_mappings(id) ON DELETE SET NULL;
ALTER TABLE "member_billing" ADD CONSTRAINT "member_billing_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "member_billing" ADD CONSTRAINT "member_billing_member_master_id_fkey" FOREIGN KEY (member_master_id) REFERENCES member_master(id) ON DELETE CASCADE;
ALTER TABLE "member_master" ADD CONSTRAINT "member_master_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "plan_mapping_groups" ADD CONSTRAINT "plan_mapping_groups_mapping_id_fkey" FOREIGN KEY (mapping_id) REFERENCES plan_mappings(id) ON DELETE CASCADE;
ALTER TABLE "plan_mappings" ADD CONSTRAINT "plan_mappings_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "plan_mappings" ADD CONSTRAINT "plan_mappings_location_id_fkey" FOREIGN KEY (location_id) REFERENCES locations(id);
ALTER TABLE "processed_event_ids" ADD CONSTRAINT "processed_event_ids_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE "reconciliation_run" ADD CONSTRAINT "reconciliation_run_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE "trace_context" ADD CONSTRAINT "trace_context_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE "webhook_log" ADD CONSTRAINT "webhook_log_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id);

-- --- Views ---

CREATE VIEW "v_trace_timeline" AS
SELECT ae.trace_id,
    ae.ts,
    'activity'::text AS source,
    ae.actor_type,
    ae.actor_id,
    ae.action AS event,
    ae.target_type,
    ae.target_id,
    ae.result,
    ae.diff AS detail,
    ae.client_id,
    tc.client_name,
    tc.member_name,
    tc.member_email,
    tc.source_platform,
    tc.hardware_platform,
    tc.hardware_user_id,
    tc.plan_name,
    tc.door_name,
    tc.entry_point
   FROM (activity_event ae
     LEFT JOIN trace_context tc ON (((tc.trace_id)::text = (ae.trace_id)::text)))
  WHERE (ae.trace_id IS NOT NULL)
UNION ALL
 SELECT wl.trace_id,
    wl.received_at AS ts,
    'webhook'::text AS source,
    wl.actor_type,
    wl.actor_id,
    wl.event_type AS event,
    'webhook'::text AS target_type,
    wl.event_id AS target_id,
    wl.hmac_status AS result,
    wl.normalized_payload AS detail,
    wl.client_id,
    tc.client_name,
    tc.member_name,
    tc.member_email,
    tc.source_platform,
    tc.hardware_platform,
    tc.hardware_user_id,
    tc.plan_name,
    tc.door_name,
    tc.entry_point
   FROM (webhook_log wl
     LEFT JOIN trace_context tc ON (((tc.trace_id)::text = wl.trace_id)))
  WHERE (wl.trace_id IS NOT NULL)
UNION ALL
 SELECT dl.trace_id,
    dl.created_at AS ts,
    'diagnostic'::text AS source,
    dl.actor_type,
    dl.actor_id,
    dl.error_code AS event,
    dl.service AS target_type,
    NULL::character varying AS target_id,
    dl.level AS result,
    dl.context AS detail,
    dl.client_id,
    tc.client_name,
    tc.member_name,
    tc.member_email,
    tc.source_platform,
    tc.hardware_platform,
    tc.hardware_user_id,
    tc.plan_name,
    tc.door_name,
    tc.entry_point
   FROM (diagnostic_log dl
     LEFT JOIN trace_context tc ON (((tc.trace_id)::text = dl.trace_id)))
  WHERE (dl.trace_id IS NOT NULL)
UNION ALL
 SELECT mal.trace_id,
    mal.created_at AS ts,
    'member_access'::text AS source,
    mal.actor_type,
    mal.actor_id,
    mal.event_type AS event,
    'member'::text AS target_type,
    (mal.member_id)::text AS target_id,
    COALESCE(mal.error_code, 'success'::character varying) AS result,
    jsonb_build_object('mapping_id', mal.mapping_id, 'hardware_group_id', mal.hardware_group_id) AS detail,
    mal.client_id,
    tc.client_name,
    tc.member_name,
    tc.member_email,
    tc.source_platform,
    tc.hardware_platform,
    tc.hardware_user_id,
    tc.plan_name,
    tc.door_name,
    tc.entry_point
   FROM (member_access_log mal
     LEFT JOIN trace_context tc ON (((tc.trace_id)::text = (mal.trace_id)::text)))
  WHERE (mal.trace_id IS NOT NULL)
UNION ALL
 SELECT eq.trace_id,
    eq.created_at AS ts,
    'error_queue'::text AS source,
    eq.actor_type,
    eq.actor_id,
    eq.event_type AS event,
    'error'::text AS target_type,
    (eq.id)::text AS target_id,
    eq.status AS result,
    jsonb_build_object('error_reason', eq.error_reason, 'error_code', eq.error_code, 'plan_name', eq.plan_name, 'door_name', eq.door_name) AS detail,
    eq.client_id,
    tc.client_name,
    tc.member_name,
    tc.member_email,
    tc.source_platform,
    tc.hardware_platform,
    tc.hardware_user_id,
    tc.plan_name,
    tc.door_name,
    tc.entry_point
   FROM (error_queue eq
     LEFT JOIN trace_context tc ON (((tc.trace_id)::text = (eq.trace_id)::text)))
  WHERE (eq.trace_id IS NOT NULL)
UNION ALL
 SELECT aal.trace_id,
    COALESCE(aal.configured_at, aal.created_at) AS ts,
    'admin_audit'::text AS source,
    aal.actor_type,
    COALESCE(aal.actor_id, aal.configured_by) AS actor_id,
    COALESCE(aal.admin_action, aal.event_type) AS event,
    aal.target_entity AS target_type,
    (aal.target_id)::text AS target_id,
    aal.result,
    aal.details AS detail,
    aal.client_id,
    tc.client_name,
    tc.member_name,
    tc.member_email,
    tc.source_platform,
    tc.hardware_platform,
    tc.hardware_user_id,
    tc.plan_name,
    tc.door_name,
    tc.entry_point
   FROM (adapter_admin_log aal
     LEFT JOIN trace_context tc ON (((tc.trace_id)::text = (aal.trace_id)::text)))
  WHERE (aal.trace_id IS NOT NULL)
UNION ALL
 SELECT cal.trace_id,
    cal.created_at AS ts,
    'config_alert'::text AS source,
    cal.actor_type,
    cal.actor_id,
    cal.alert_type AS event,
    'config'::text AS target_type,
    (cal.plan_mapping_id)::text AS target_id,
        CASE
            WHEN (cal.resolved_at IS NULL) THEN 'open'::text
            ELSE 'resolved'::text
        END AS result,
    jsonb_build_object('hardware_ref', cal.hardware_ref, 'affected_member_count', cal.affected_member_count) AS detail,
    cal.client_id,
    tc.client_name,
    tc.member_name,
    tc.member_email,
    tc.source_platform,
    tc.hardware_platform,
    tc.hardware_user_id,
    tc.plan_name,
    tc.door_name,
    tc.entry_point
   FROM (config_alert_log cal
     LEFT JOIN trace_context tc ON (((tc.trace_id)::text = (cal.trace_id)::text)))
  WHERE (cal.trace_id IS NOT NULL)
  ORDER BY 2 DESC;
